<?php

namespace App\Controller\Admin;

use App\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\MoneyField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class ProductCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Product::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('name'),
            MoneyField::new('price')->setCurrency('EUR'),
            TextEditorField::new('description'),
            NumberField::new('reference'),
            NumberField::new('stock'),
            TextField::new('slug'),
            BooleanField::new('active')->setValue('1'),
            ImageField::new('mainImage')
                ->onlyOnIndex()
                ->setBasePath("/assets/img/product/mainImg"),
            ImageField::new('mainImage')
                ->onlyOnForms()
                ->setUploadDir("public/assets/img/product/mainImg")
                ->setBasePath("/assets")
                ->setRequired(false)
                ->setUploadedFileNamePattern("[contenthash].[extension]"),
            AssociationField::new('category')
            ->setFormTypeOption('choice_label','name'),
            AssociationField::new('status')
                ->setFormTypeOption('choice_label','name'),
            DateTimeField::new("modifiedAt")->hideOnForm(),
            DateTimeField::new("createdAt")->hideOnForm(),
        ];
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if (!$entityInstance instanceof Product) return;

        $entityInstance->setCreatedAt(new \DateTimeImmutable);
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if (!$entityInstance instanceof Product) return;

        $entityInstance->setModifiedAt(new \DateTimeImmutable);

        parent::updateEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }
}
